### ISSUE TITLE
Undo

### ISSUE THREAD

**Issue by hparfr** [pjdietz/rester-sublime-http-client#22]
With sublimetext 2 on Mac OS X.

When I run RESTer: HTTP Request from the palette or from the shortcut, it will do a "undo" in the document after processing the command.

For instance, 
* create a new document
* enter "localhost"
* run RESTer from the palette

* A new document with the response will open.
* In the first document, the content is now "localhos" instead of "localhost"

I then changed the key binding to something else, the issue still appears.
Tested against master, 1.8.0, 1.7.0 and 1.6.0

**Comment by pjdietz** [comment]
Thanks for catching this. 1.8.2 should fix this.

RESTer uses the undo stack to modify the request before sending (e.g., form encoding) and then undo it back to your original. ST3's API provides more direct access, but my workaround for ST2 was doing an undo even when no actual change took place.
